### ISSUE TITLE
Improve free space handling for swap growth

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/ansible-playbooks#101]
Some older workstations don't have enough free space for our current default swapsize, which results in them being stuck at 2GB. We should add some logic to allow fallback to another reasonable increased size (8GB?)

**Comment by thomasbeaudry** [comment]
there was logic added, see:  https://github.com/DouglasNeuroInformatics/ansible-playbooks/pull/90/commits/584561f7248b3a3166f9386d2757165c4e580c3e

**Comment by gdevenyi** [comment]
Ok, I see the issue, defaulting to 2GB is a bit too low. I'd say try for 8, then 4, then 2
