### ISSUE TITLE
Add netdata smartd monitoring

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/ansible-playbooks#38]
Doesn't seem to be notifying about smart issues.

**Comment by thomasbeaudry** [comment]
What metrics would you want?  There are a lot:


Metric | Dimensions | Unit | SCSI | ATA
-- | -- | -- | -- | --
smartd_log.read_error_rate | a dimension per device | value |   | •
smartd_log.seek_error_rate | a dimension per device | value |   | •
smartd_log.soft_read_error_rate | a dimension per device | errors |   | •
smartd_log.write_error_rate | a dimension per device | value |   | •
smartd_log.read_total_err_corrected | a dimension per device | errors | • |  
smartd_log.read_total_unc_errors | a dimension per device | errors | • |  
smartd_log.write_total_err_corrected | a dimension per device | errors | • |  
smartd_log.write_total_unc_errors | a dimension per device | errors | • |  
smartd_log.verify_total_err_corrected | a dimension per device | errors | • |  
smartd_log.verify_total_unc_errors | a dimension per device | errors | • |  
smartd_log.sata_interface_downshift | a dimension per device | events |   | •
smartd_log.udma_crc_error_count | a dimension per device | errors |   | •
smartd_log.throughput_performance | a dimension per device | value |   | •
smartd_log.seek_time_performance | a dimension per device | value |   | •
smartd_log.start_stop_count | a dimension per device | events |   | •
smartd_log.power_on_hours_count | a dimension per device | hours |   | •
smartd_log.power_cycle_count | a dimension per device | events |   | •
smartd_log.unexpected_power_loss | a dimension per device | events |   | •
smartd_log.spin_up_time | a dimension per device | ms |   | •
smartd_log.spin_up_retries | a dimension per device | retries |   | •
smartd_log.calibration_retries | a dimension per device | retries |   | •
smartd_log.airflow_temperature_celsius | a dimension per device | celsius |   | •
smartd_log.temperature_celsius | a dimension per device | celsius | • | •
smartd_log.reallocated_sectors_count | a dimension per device | sectors |   | •
smartd_log.reserved_block_count | a dimension per device | percentage |   | •
smartd_log.program_fail_count | a dimension per device | errors |   | •
smartd_log.erase_fail_count | a dimension per device | failures |   | •
smartd_log.wear_leveller_worst_case_erase_count | a dimension per device | erases |   | •
smartd_log.unused_reserved_nand_blocks | a dimension per device | blocks |   | •
smartd_log.reallocation_event_count | a dimension per device | events |   | •
smartd_log.current_pending_sector_count | a dimension per device | sectors |   | •
smartd_log.offline_uncorrectable_sector_count | a dimension per device | sectors |   | •
smartd_log.percent_lifetime_used | a dimension per device | percentage |   | •
smartd_log.media_wearout_indicator | a dimension per device | percentage |   | •
smartd_log.nand_writes_1gib | a dimension per device | GiB |   | •

**Comment by gdevenyi** [comment]
All of them?
