### ISSUE TITLE
Still getting netdata apcupsd battery charge emails

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/ansible-playbooks#52]

**Comment by gdevenyi** [comment]
These are the relevant status codes the daemon sets:
```
     // Now output status in human readable form
     statstr = "";
     if (status & UPS_calibration)
        statstr += "CAL ";
     if (status & UPS_trim)
        statstr += "TRIM ";
     if (status & UPS_boost)
        statstr += "BOOST ";
     if (status & UPS_online)
        statstr += "ONLINE ";
     if (status & UPS_onbatt)
*       statstr += "ONBATT ";
     if (status & UPS_overload)
        statstr += "OVERLOAD ";
     if (status & UPS_battlow)
        statstr += "LOWBATT ";
     if (status & UPS_replacebatt)
        statstr += "REPLACEBATT ";
     if (!(status & UPS_battpresent))
        statstr += "NOBATT ";

     // This overrides the above
     if (status & UPS_commlost) {
        statstr = "COMMLOST";
        battstat = -1;
     }

     // This overrides the above
     if (status & UPS_shutdown)
        statstr = "SHUTTING DOWN";

     // This overrides the above
     if (status & UPS_onbatt) {
        astring reason = Get("LASTXFER");
        if (strstr(reason, "self test"))
           statstr = "SELFTEST";
     }
```

We should be sending notifications on the "bad" ones above and/or if the batter gets very low (<25%)

**Comment by thomasbeaudry** [comment]
I just got kicked out of the gateway so I can't show you my code, but I have 2 netdata alerts.  1 of them was sent to you yesterday, but the text for the units was too long, and it did some funky text wrapping/overlapping.  But essentially the email said:

Raised to Critical, apcupsd_status_code = 0 code (0=ONLINE,1=ONBATT,2=OVERLOAD,3=LOWBATT,4=REPLACEBATT,5=NOBATT,6=SLAVE,7=SLAVEDOWN,8=COMMLOST,9=SHUTTING DOWN), on cicws45

So email gets triggered when the status code is no longer is 0 == ONLINE.  

I'm assuming that #1-9 are all "bad", but i guess you just want #2-6 instead?

This fix that the PR is handling is reporting that the battery level is less than 75%.  It seems like you want it to be 25%, so i'll make the change shortly when i can get back onto the gateway
