### ISSUE TITLE
Netdata track failed logins

### ISSUE THREAD

**Issue by gdevenyi** [DouglasNeuroInformatics/ansible-playbooks#57]
On all systems
(ansible doesn't manage cicus03, cicus04, cicss05, cicss06 yet)

**Comment by thomasbeaudry** [comment]
this is for all failed logins or only certain users?  Also, only ssh attempts?

**Comment by gdevenyi** [comment]
All users. All methods

**Comment by thomasbeaudry** [comment]
that's going to be a lot of emails!
