### ISSUE TITLE
Install the terminal text editor neovim

### ISSUE THREAD

**Issue by zklsmr** [DouglasNeuroInformatics/ansible-playbooks#67]
Is it possible to install [neovim](https://github.com/neovim/neovim) ?

It is a tiny terminal-based text editor that is highly extensible and easy to use, especially for **remote work** where vscode and vim lack fluidity and seamless integration.  

Thanks!

**Comment by gdevenyi** [comment]
neovim has been deployed on all systems and added to the base deployment scripts.
